### ISSUE TITLE
Spacing reduced before headings with customids

### ISSUE THREAD

**Issue by Vanderhoof** [foliant-docs/foliantcontrib.customids#4]
When I add cutomids to headings **level4 and higher** in my MkDocs project, the spacing before these headings is reduced in ugly way:

**Without customids:**

![Before](https://user-images.githubusercontent.com/12543857/55465980-f44d2600-5606-11e9-918f-f6533dd6480a.png) 

**With customids:**

![After](https://user-images.githubusercontent.com/12543857/55465992-fc0cca80-5606-11e9-9586-46e3ee3e0806.png)

---

**Without customids:**

![Before](https://user-images.githubusercontent.com/12543857/55466010-062ec900-5607-11e9-8bd6-be54247605fc.png)

**With customids:**

![After](https://user-images.githubusercontent.com/12543857/55466017-0af37d00-5607-11e9-9473-91382522b362.png)

**Comment by artlomov** [comment]
Fixed in version 1.0.6.
